version: '3' # Version of the Docker Compose file format
services:
  elemental_pay_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      - VIRTUAL_HOST=api.elemental-pay.local
      - VIRTUAL_PORT=4040
      - NODE_ENV=development
      - APP_ENV=local
  elemental_pay_web:
    build:
      context: ./packages/web
      target: dev
    command: npm run dev
    environment:
      - VIRTUAL_HOST=elemental-sso.local
      - VIRTUAL_PORT=3000
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_ENV=local
    volumes:
      - ./packages/web:/app
      - /app/node_modules
      - /app/.next
