version: '3'
services:
  web:
    build: ./
    environment:
      - PORT=3000
    networks:
      - elemental_pay_net
      - elemental_pay_next_net
networks:
  elemental_pay_net:
  elemental_pay_next_net:
    external: true
    driver: bridge
