version: '3'
services:
  web:
    build: ./
    environment:
      - PORT=3010
    networks:
      - elemental_net
      - elemental_pay_net
networks:
  elemental_pay_net:
  elemental_net:
    external: true
    driver: bridge
